apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: grafana-ingress
  namespace: monitoring
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/grafana(/|$)(.*)"
        backend:
          service:
            name: grafana
            port:
              number: 3000           
