repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 6.6.0
    values:
      - argocd/values.yaml
  - name: argocd-image-updater
    namespace: argocd
    chart: argo/argocd-image-updater
    version: 0.11.0
    values:
      - ../../values/argocd-image-updater.yaml
  - name: argocd-extra
    namespace: argocd
    chart: ./argocd-extra
    values:
      - argocd-extra/values.yaml