apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 6.6.0
    helm:
      values: |
        configs:
          cmp:
            create: true
            plugins:
              helmfile:
                discover:
                  fileName: helmfile.yaml
                generate:
                  command:
                    - bash
                    - "-c"
                  args:
                    - helmfile -q template --include-crds --skip-tests
  syncPolicy:
    automated:
      selfHeal: true