apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/ureuzy/playground.git
    path: manifests/argocd/base
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true