apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 2.11.1
    chart: eck-operator
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true