apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  project: default
  source:
    repoURL: https://github.com/ureuzy/playground.git
    path: manifests/ingress-nginx/base
    targetRevision: main    
  syncPolicy:
    automated:
      selfHeal: true