---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-event-exporter
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubernetes-event-exporter
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: "2.4.8"
    helm:
      values: |
        config:
          logLevel: debug
          logFormat: pretty
          receivers:
            - name: slack
              slack:
                token: ${SLACK_TOKEN}
                channel: memo
                message: "{{ `{{ .Message }}` }}"
                fields:
                  namespace: "{{ `{{ .Namespace }}` }}"
                  reason: "{{ `{{ .Reason }}` }}"
                  kind: "{{ `{{ .InvolvedObject.Kind }}` }}"
                  object: "{{ `{{ .InvolvedObject.Name }}` }}"
          route:
            routes:
              - match:
                  - receiver: slack
                    reason: "OOMKilled"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---