---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-event-exporter
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kubernetes-event-exporter
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: "2.4.8"
    helm:
      values: |
        config:
          logLevel: debug
          logFormat: pretty
          receivers:
            - name: slack
              webhook:
                endpoint: ${ENDPOINT}
                layout:
                  attachments:
                    - color: "#D00000"
                      fields:
                        - title: "Message"
                          value: "{{ `{{ .Message }}` }}"
                        - title: "FirstTimestamp"
                          value: "{{ `{{ .FirstTimestamp }}` }}"        
                        - title: "Namespace"
                          value: "{{ `{{ .Namespace }}` }}"
                          short: true
                        - title: "Reason"
                          value: "{{ `{{ .Reason }}` }}"
                          short: true
                        - title: "Kind"
                          value: "{{ `{{ .InvolvedObject.Kind }}` }}"
                          short: true
                        - title: "Object"
                          value: "{{ `{{ .InvolvedObject.Name }}` }}"
                          short: true
          route:
            routes:
              - match:
                  - receiver: slack
                    reason: "Created"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
---