apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/grafana/helm-charts.git
    targetRevision: main
    path: charts/loki-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true