apiVersion: kustomize.config.k8s.io/v1beta1
kind: Deployment
metadata:
  name: deployment-test
spec:
  template:
    metadata:
      labels:
        app: deployment-test
    spec:
      containers:
        - name: nginx
          image: nginx:alpine