apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: projectcontour
resources:
  - https://raw.githubusercontent.com/projectcontour/contour/release-1.22/examples/render/contour.yaml
