apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: kube-prometheus-stack-40.0.0
    path: charts/prometheus
    helm:
      values: |
        server:
          image:
            repository: quay.io/prometheus/prometheus
            tag: v2.36.2  
          ingress:
            enabled: true
            path: /
            hosts:
              - prometheus.local.com
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true