apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: GF_SERVER_ROOT_URL
        value: "http://localhost/grafana"
  target:
    kind: Deployment
    namespace: monitoring
    name: grafana  
