# apiVersion: v1
# kind: Secret
# metadata:
#   name: grafana-config
#   namespace: monitoring
# stringData:
#   grafana.ini: |
#     [date_formats]
#     default_timezone = UTC
#     [server]
#     domain = localhost
#     root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
#     serve_from_sub_path = true